# Generated by Django 4.2.19 on 2025-02-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemail",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Доставлено"), (2, "Прочитано")],
                default=1,
                verbose_name="Статус доставки",
            ),
        ),
    ]
